name: CD

on:
  push:
    branches: [main]

jobs:
  Deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Build Notely binary
        run: ./scripts/buildprod.sh

      # Fake GCP setup (lokal simuliert)
      - name: Setup Fake GCP Credentials
        run: echo "${{ secrets.GCP_CREDENTIALS }}" > fake-gcp-credentials.json

      - name: Build Docker image
        run: docker build -t local-ar/notely:latest .

      - name: Push to Fake Artifact Registry
        run: docker save local-ar/notely:latest -o artifact-registry/notely-ar-repo/notely_latest.tar
